os:
  - linux
  - osx

language: node_js
cache: yarn
node_js:
  - '8.12.0'
  - 'lts/*'
  - 'node'

install:
  - yarn --ignore-engines --frozen-lockfile

script:
  - npm run build
  - npm run lint
  - npm run test
  - npm run coveralls
